---
clickhouse:
  hosts:
    clickhouse-01:
      # ansible_host: clickhouse-01
      # ansible_connection: docker
      ansible_host: 158.160.196.9
      ansible_user: nimda

vector:
  hosts:
    vector-01:
      # ansible_host: vector-01
      # ansible_connection: docker
      ansible_host: 158.160.199.141
      ansible_user: nimda

lighthouse:
  hosts:
    lighthouse-01:
      # ansible_host: lighthouse-01
      # ansible_connection: docker
      ansible_host: 158.160.199.197
      ansible_user: nimda