#SPDX-License-Identifier: MIT-0
---
# tasks file for create_file

- name: Create file using custom module
  my_own_namespace.yandex_cloud_elk.my_own_module:
    path: "{{ file_path }}"
    content: "{{ file_content }}"
    mode: "{{ file_mode | default('0644') }}"